// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace IDisposableSourceGenerator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class IDisposableGeneratorAttributeTemplate : IDisposableGeneratorAttributeTemplateBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("// <auto-generated>\r\n// THIS (.cs) FILE IS GENERATED BY IDISPOSABLEGENERATOR. DO " +
                    "NOT CHANGE IT.\r\n// </auto-generated>\r\n#nullable enable\r\nusing System;\r\nusing Sys" +
                    "tem.Collections.Generic;\r\n\r\nnamespace IDisposableSourceGenerator\r\n{\r\n    [Attrib" +
                    "uteUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]\r\n   " +
                    " internal sealed class IDisposableGeneratorAttribute : Attribute\r\n    {\r\n       " +
                    " public Type? CompositeDisposableType { get; }\r\n        public string? Composite" +
                    "DisposableFieldName { get; }\r\n        public IDisposableGeneratorOptions Options" +
                    " { get; }\r\n\r\n        public IDisposableGeneratorAttribute(\r\n            Type? co" +
                    "mpositeDisposableType = null,\r\n            string? compositeDisposableFieldName " +
                    "= null,\r\n            IDisposableGeneratorOptions options = IDisposableGeneratorO" +
                    "ptions.None)\r\n        {\r\n            this.CompositeDisposableType = compositeDis" +
                    "posableType ?? typeof(IDisposableSourceGenerator.SimpleCompositeDisposable);\r\n  " +
                    "          this.CompositeDisposableFieldName = string.IsNullOrWhiteSpace(composit" +
                    "eDisposableFieldName) ? \"_disposables\" : compositeDisposableFieldName!;\r\n       " +
                    "     this.Options = options;\r\n        }\r\n    }\r\n\r\n    [Flags]\r\n    internal enum" +
                    " IDisposableGeneratorOptions\r\n    {\r\n        None = 0x0000,\r\n        DisposeUnma" +
                    "nagedObjectsMethod = 0x0001,     // DisposeUnmanagedObjects()\r\n        SetLargeF" +
                    "ieldsToNullMethod = 0x0002,        // SetLargeFieldsToNull()\r\n        OnDisposin" +
                    "gMethod = 0x0004,                 // OnDisposing()\r\n    }\r\n\r\n    /// <summary>Ma" +
                    "nages multiple IDisposable objects</summary>\r\n    internal class SimpleComposite" +
                    "Disposable : IDisposable, ICollection<IDisposable>\r\n    {\r\n        private reado" +
                    "nly List<IDisposable> _disposables = new List<IDisposable>();\r\n        private b" +
                    "ool _disposed;\r\n        private readonly object _lockObject = new object();\r\n\r\n " +
                    "       /// <summary>Gets the enumerator of the IDisposable collection.</summary>" +
                    "\r\n        /// <returns>IEnumerator&lt;IDisposable&gt;</returns>\r\n        public " +
                    "IEnumerator<IDisposable> GetEnumerator()\r\n        {\r\n            ThrowExceptionI" +
                    "fDisposed();\r\n            lock (_lockObject)\r\n            {\r\n                ret" +
                    "urn ((IEnumerable<IDisposable>)_disposables.ToArray()).GetEnumerator();\r\n       " +
                    "     }\r\n        }\r\n\r\n        System.Collections.IEnumerator System.Collections.I" +
                    "Enumerable.GetEnumerator()\r\n        {\r\n            ThrowExceptionIfDisposed();\r\n" +
                    "            lock (_lockObject)\r\n            {\r\n                return ((IEnumera" +
                    "ble<IDisposable>)_disposables.ToArray()).GetEnumerator();\r\n            }\r\n      " +
                    "  }\r\n\r\n        /// <summary>Add an object at the end</summary>\r\n        /// <par" +
                    "am name=\"item\">Objects to add</param>\r\n        public void Add(IDisposable item)" +
                    "\r\n        {\r\n            if (item is null) throw new ArgumentNullException(nameo" +
                    "f(item));\r\n\r\n            ThrowExceptionIfDisposed();\r\n            lock (_lockObj" +
                    "ect)\r\n            {\r\n                _disposables.Add(item);\r\n            }\r\n   " +
                    "     }\r\n\r\n        /// <summary>Delete all objects</summary>\r\n        public void" +
                    " Clear()\r\n        {\r\n            ThrowExceptionIfDisposed();\r\n            lock (" +
                    "_lockObject)\r\n            {\r\n                _disposables.Clear();\r\n            " +
                    "}\r\n        }\r\n\r\n        /// <summary>Determine if an objects is included in this" +
                    " collection or not</summary>\r\n        /// <param name=\"item\">Elements that you w" +
                    "ant to determine if they are included in the collection</param>\r\n        /// <re" +
                    "turns>Whether or not it is included</returns>\r\n        public bool Contains(IDis" +
                    "posable item)\r\n        {\r\n            if (item is null) throw new ArgumentNullEx" +
                    "ception(nameof(item));\r\n\r\n            ThrowExceptionIfDisposed();\r\n            l" +
                    "ock (_lockObject)\r\n            {\r\n                return _disposables.Contains(i" +
                    "tem);\r\n            }\r\n        }\r\n\r\n        /// <summary>\r\n        /// Copies the" +
                    " entire array to a compatible one-dimensional array. The copy operation starts f" +
                    "rom the specified index of the destination array.\r\n        /// </summary>\r\n     " +
                    "   /// <param name=\"array\">Copy destination array</param>\r\n        /// <param na" +
                    "me=\"arrayIndex\">Index of where in the destination array to perform the copy oper" +
                    "ation from</param>\r\n        public void CopyTo(IDisposable[] array, int arrayInd" +
                    "ex)\r\n        {\r\n            ThrowExceptionIfDisposed();\r\n            lock (_lock" +
                    "Object)\r\n            {\r\n                _disposables.CopyTo(array, arrayIndex);\r" +
                    "\n            }\r\n        }\r\n\r\n        /// <summary>Get the number of objects actu" +
                    "ally stored</summary>\r\n        public int Count\r\n        {\r\n            get\r\n   " +
                    "         {\r\n                ThrowExceptionIfDisposed();\r\n                lock (_" +
                    "lockObject)\r\n                {\r\n                    return _disposables.Count;\r\n" +
                    "                }\r\n            }\r\n        }\r\n\r\n        /// <summary>Gets whether" +
                    " this collection is read-only or not. (Always returns false)</summary>\r\n        " +
                    "public bool IsReadOnly\r\n        {\r\n            get\r\n            {\r\n             " +
                    "   ThrowExceptionIfDisposed();\r\n                return false;\r\n            }\r\n  " +
                    "      }\r\n\r\n        /// <summary>Deletes the first specific object found.</summar" +
                    "y>\r\n        /// <param name=\"item\">Object to be deleted</param>\r\n        /// <re" +
                    "turns>whether it was possible to delete it</returns>\r\n        public bool Remove" +
                    "(IDisposable item)\r\n        {\r\n            if (item is null) throw new ArgumentN" +
                    "ullException(nameof(item));\r\n\r\n            ThrowExceptionIfDisposed();\r\n\r\n      " +
                    "      lock (_lockObject)\r\n            {\r\n                return _disposables.Rem" +
                    "ove(item);\r\n            }\r\n        }\r\n\r\n        /// <summary>Dispose all the obj" +
                    "ects in this collection</summary>\r\n        public void Dispose()\r\n        {\r\n   " +
                    "         Dispose(disposing: true);\r\n            GC.SuppressFinalize(this);\r\n    " +
                    "    }\r\n\r\n        /// <summary>dispose method</summary>\r\n        /// <param name=" +
                    "\"disposing\"></param>\r\n        protected virtual void Dispose(bool disposing)\r\n  " +
                    "      {\r\n            if (_disposed) return;\r\n\r\n            if (disposing)\r\n     " +
                    "       {\r\n                lock (_lockObject)\r\n                {\r\n               " +
                    "     _disposables.ForEach(item => item.Dispose());\r\n                }\r\n         " +
                    "   }\r\n            _disposed = true;\r\n        }\r\n\r\n        /// <summary>throw exc" +
                    "eption if disposed</summary>\r\n        protected void ThrowExceptionIfDisposed()\r" +
                    "\n        {\r\n            if (_disposed)\r\n                throw new ObjectDisposed" +
                    "Exception(nameof(SimpleCompositeDisposable));\r\n        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class IDisposableGeneratorAttributeTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
